# Utiliza la imagen oficial de Node.js como base para el servidor
FROM node:14

# Establece el directorio de trabajo dentro del contenedor para el servidor
WORKDIR /app

# Copia los archivos del servidor al contenedor
COPY package.json package-lock.json /app/
COPY . /app/

# Instala las dependencias del servidor
RUN npm install

# Expone el puerto 4000 (puerto en el que se ejecuta el servidor)
EXPOSE 4000

# Inicia el servidor cuando se inicie el contenedor
CMD ["npm", "start"]
